name: Build Linux App

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
        
    - name: Install frontend dependencies
      run: npm ci
      
    - name: Install Rust dependencies
      run: cargo fetch
      working-directory: src-tauri
      
    - name: Run frontend build
      run: npm run build
      
    - name: Run Tauri build
      run: npm run tauri:build
      working-directory: .
      env:
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        
    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: pathfinder-linux-appimage-${{ github.sha }}
        path: src-tauri/target/release/bundle/appimage/*.AppImage
        retention-days: 30
        
    - name: Upload DEB package
      uses: actions/upload-artifact@v4
      with:
        name: pathfinder-linux-deb-${{ github.sha }}
        path: src-tauri/target/release/bundle/deb/*.deb
        retention-days: 30
        
    - name: Upload RPM package
      uses: actions/upload-artifact@v4
      with:
        name: pathfinder-linux-rpm-${{ github.sha }}
        path: src-tauri/target/release/bundle/rpm/*.rpm
        retention-days: 30
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      continue-on-error: true
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src-tauri/target/release/bundle/appimage/*.AppImage
          src-tauri/target/release/bundle/deb/*.deb
          src-tauri/target/release/bundle/rpm/*.rpm
        generate_release_notes: true
        draft: true
        tag_name: v${{ github.run_number }}
        name: PathFinder v${{ github.run_number }}
